Worked on bash-completion files for apt.

diff --git a/rootfs/etc/bash_completion.d/apt-cache-aliases b/rootfs/etc/bash_completion.d/apt-cache-aliases
--- a/rootfs/etc/bash_completion.d/apt-cache-aliases
+++ b/rootfs/etc/bash_completion.d/apt-cache-aliases
@@ -2,64 +2,68 @@
 
 _apt_cache_mod()
 {
-    local cur prev words cword
-    _init_completion || return
+   local cur prev words cword
+   _init_completion || return
 
-    local special
-    special=${words[0]}
-    special=${special:4}
-    [[ "${special}" == "search-names" ]] && special="search"
+   ## Get program command (apt-...)
+   local special
+   special=${words[0]}
+   special=${special:4}
+   [[ "${special}" == "search-names" ]] && special="search"
 
-		if [[ "${prev:0:4}" == "apt-" ]]; then
-			prev="${prev:4}"
-		fi
+   ## Cleanup 'apt-' prefix
+   if [[ "${prev:0:4}" == "apt-" ]]; then
+      prev="${prev:4}"
+   fi
 
-    case $prev in
-             -c|-p|-s|--config-file|--pkg-cache|--src-cache)
-                 _filedir
-                 return 0
-                 ;;
-             search)
-                 if [[ "$cur" != -* ]]; then
-                    return 0
-                 fi
-                 ;;
-    esac
+   ## If previous command has any special effect to this argument
+   case $prev in
+   -c|-p|-s|--config-file|--pkg-cache|--src-cache)
+      _filedir
+      return 0
+   ;;
+   search)
+      if [[ "$cur" != -* ]]; then
+         COMPREPLY=( $( apt-cache --no-generate pkgnames "$cur" 2> /dev/null ) )
+         return 0
+      fi
+   ;;
+   esac
 
-		if [[ "$cur" == -* ]]; then
+   ## If argument is part of a flag
+   if [[ "$cur" == -* ]]; then
+      COMPREPLY=( $( compgen -W '-h -v -p -s -q -i -f -a -g -c \
+                             -o --help --version --pkg-cache --src-cache \
+                             --quiet --important --full --all-versions \
+                             --no-all-versions --generate --no-generate \
+                             --names-only --all-names --recurse \
+                             --config-file --option --installed' -- "$cur" ) )
 
-        COMPREPLY=( $( compgen -W '-h -v -p -s -q -i -f -a -g -c \
-                -o --help --version --pkg-cache --src-cache \
-                --quiet --important --full --all-versions \
-                --no-all-versions --generate --no-generate \
-                --names-only --all-names --recurse \
-                --config-file --option --installed' -- "$cur" ) )
+      return 0
+   fi
 
-				return 0
-    fi
+   ## If command has a special effect
+   if [[ -n $special ]]; then
+      case $special in
+      add)
+         _filedir
+         return 0
+      ;;
 
-    if [[ -n $special ]]; then
-        case $special in
-        add)
-            _filedir
-            return 0
-            ;;
+      showsrc)
+         COMPREPLY=( $( apt-cache dumpavail | \
+            command grep "^Source: $cur" | sort -u | cut -f2 -d" " ) )
+         return 0
+      ;;
 
-        showsrc)
-            COMPREPLY=( $( apt-cache dumpavail | \
-                command grep "^Source: $cur" | sort -u | cut -f2 -d" " ) )
-            return 0
-            ;;
+      *)
+         COMPREPLY=( $( apt-cache --no-generate pkgnames "$cur" 2> /dev/null ) )
+         return 0
+      ;;
+      esac
+   fi
 
-        *)
-            COMPREPLY=( $( apt-cache --no-generate pkgnames "$cur" 2> /dev/null ) )
-            return 0
-            ;;
-
-        esac
-    fi
-
-    return 0
+   return 0
 } &&
 complete -F _apt_cache_mod apt-search &&
 complete -F _apt_cache_mod apt-search-names &&
