The install script is nearly complete. I'm working now on the linux script.

diff --git a/scripts/linux b/scripts/linux
--- a/scripts/linux
+++ b/scripts/linux
@@ -3,6 +3,7 @@
 # this file, and for a DISCLAIMER OF ALL WARRANTIES.
 
 #sdcard="$(readlink -f /sdcard)"
+home="$ANDROID_DATA/local"
 system="$(basename $0)"
 mnt="$ANDROID_DATA/local/$system"
 imgtype="ext2"
@@ -14,7 +15,6 @@ export PATH="$xbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:
 export TERM="xterm-color"
 export HOME="/root"
 
-home="$ANDROID_DATA/local"
 
 if [ -z "$SECONDARY_STORAGE" ]; then
   sdcard="$EXTERNAL_STORAGE"
@@ -44,42 +44,215 @@ for i in $(seq 250 -1 0); do
 done
 }
 
-kit="$(currentscriptpath)"
-img="$kit/$system.img"
+#kit="$(currentscriptpath)"
+#img="$kit/$system.img"
 
-
-#Froyo's apps-to-SD makes use of special loopback devices /dev/block/dm-#
-#Each program installed to SD uses up a normal loopback device.
-#We therefore have to make our own with a minor number that we hope
-#users will never reach.
-#Our mount will break if there are $loopno apps installed to SD
 
 if [ "$1" != "install" ]; then
-  if [ -e "$home/linuxonandroid/config.default" ]; then
-    . "$home/linuxonandroid/config.default"
+  ##-------------------------Check Arguments--------------------------##
+  for (( i=$((BASH_ARGC - 1)); $((i >= 0)); i=$((i - 1)) )); do
+    if [ "$(echo "${BASH_ARGV[$i]}" | head -c 2)" == "--" ];then
+      case "$arg" in
+      ##-----------------------Config Path----------------------------##
+      --config)
+        echo "WARNING: Do not change the default config path."
+        i=$((i - 1))
+        config_path="${BASH_ARGV[$i]}"
+        break
+      ;;
+      ##-----------------------System User Home-----------------------##
+      --home)
+        echo "WARNING: Do not change the default home path."
+        i=$((i - 1))
+        arg_home="${BASH_ARGV[$i]}"
+      ;;
+      esac
+    fi
+  done
+  
+  
+  if [ -z "$config_path" ]; then
+    config_path="$home/linuxonandroid"
   fi
-  if [ -e "$home/linuxonandroid/config.$system" ]; then
-    . "$home/linuxonandroid/config.$system"
+  
+  
+  #Froyo's apps-to-SD makes use of special loopback devices /dev/block/dm-#
+  #Each program installed to SD uses up a normal loopback device.
+  #We therefore have to make our own with a minor number that we hope
+  #users will never reach.
+  #Our mount will break if there are $loopno apps installed to SD
+
+  if [ -e "$config_path/config.default" ]; then
+    . "$config_path/config.default"
+  fi
+  if [ -e "$config_path/config.$system" ]; then
+    . "$config_path/config.$system"
   fi
 fi
 
+
+
+
+##---------------------------Check Arguments--------------------------##
+for (( i=$((BASH_ARGC - 1)); $((i >= 0)); i=$((i - 1)) )); do
+  curr_arg="${BASH_ARGV[$i]}"
+  if [ -z "$curr_arg" ]; then
+    :
+  elif [ "$curr_arg" == "-h" ] || [ "$curr_arg" == "--help" ]; then
+    arg_help=true
+    break
+  elif [ "$(echo "$curr_arg" | head -c 2)" == "--" ];then
+    case "$arg" in
+    ##-------------------------Architecture---------------------------##
+    #--android)
+    #  arg_android="true"
+    #;;
+    ##-------------------------Architecture---------------------------##
+    --architecture)
+      i=$((i - 1))
+      architecture="${BASH_ARGV[$i]}"
+      arg_arch="true"
+    ;;
+    ##-------------------------Config Path----------------------------##
+    --config)
+      echo "WARNING: Do not change the default config path."
+      i=$((i - 1))
+      config_path="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------System User Home-----------------------##
+    --home)
+      echo "WARNING: home"
+      i=$((i - 1))
+      arg_home="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------Image Path-----------------------------##
+    --img)
+      i=$((i - 1))
+      img="${BASH_ARGV[$i]}"
+      arg_img="true"
+    ;;
+    ##-------------------------Initialize-----------------------------##
+    --init)
+      arg_init="true"
+    ;;
+    ##-------------------------Mount Path-----------------------------##
+    --mnt)
+      i=$((i - 1))
+      mnt="${BASH_ARGV[$i]}"
+      arg_mnt="true"
+    ;;
+    ##-------------------------Mount Path-----------------------------##
+    --mnt-options)
+      i=$((i - 1))
+      imgoptions="${BASH_ARGV[$i]}"
+      arg_imgoptions="true"
+    ;;
+    ##-------------------------Use native mount-----------------------##
+    --native)
+      native="true"
+    ;;
+    ##-------------------------Use native mount-----------------------##
+    --partition)
+      i=$((i - 1))
+      partition="${BASH_ARGV[$i]}"
+      arg_partition="true"
+    ;;
+    ##-------------------------System Name----------------------------##
+    --system)
+      if [ "$1" == "install" ]; then
+        # The script must be installed or renamed to work correctly
+        arg_system="true"
+        i=$((i - 1))
+        system="${BASH_ARGV[$i]}"
+      fi
+    ;;
+    ##-------------------------System Name----------------------------##
+    --type)
+      # The script must be installed or renamed to work correctly
+      arg_imgtype="true"
+      i=$((i - 1))
+      imgtype="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------Install Path of linux Script-----------##
+    --bin)
+      i=$((i - 1))
+      arg_bin="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------System TERM----------------------------##
+    --term)
+      i=$((i - 1))
+      arg_term="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------System PATH----------------------------##
+    --path)
+      i=$((i - 1))
+      arg_path_abs="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------System PATH----------------------------##
+    --pre-path)
+      i=$((i - 1))
+      arg_path_pre="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------System PATH----------------------------##
+    --post-path)
+      i=$((i - 1))
+      arg_path_post="${BASH_ARGV[$i]}"
+    ;;
+    ##-------------------------Unknown Argument-----------------------##
+    #*)
+    #  echo -e "$0: unknown argument: $curr_arg\n"
+    #  "$0" -h
+    #  exit 2 #TODO set the standard return value for this case
+    #;;
+    esac
+  elif [ "$(echo -"$curr_arg" | head -c 2)" == "--" ];then
+    args="$(echo -"$curr_arg" | awk 'BEGIN{FS=""}{ for (i = 3; i <= NF; ++i) print $i; }')"
+  
+    for arg in `echo -e "$args"`; do
+      case "$arg" in
+    ##-------------------------System Name----------------------------##
+      s)
+        arg_system="true"
+        i=$((i - 1))
+        system="${BASH_ARGV[$i]}"
+      ;;
+      ##-----------------------Unknown--------------------------------##
+      #*)
+      #  echo -e "$0: unknown argument: -$arg\n"
+      #  "$0" -h
+      #  exit 2 #TODO set the standard return value for this case
+      #;;
+      esac
+    done
+  #else
+    ##-------------------------Unknown Argument-----------------------##
+    #echo -e "$0: unknown argument: $curr_arg\n"
+    #"$0" -h
+    #exit 2 #TODO set the standard return value for this case
+  fi
+done
+
+
+
+
 case "$1" in
 mount)
-  if [ ! -e "$home/linuxonandroid/config.$system" ]; then
+  if [ ! -e "$config_path/config.$system" ]; then
     "$0" install "$system"
-    . "$home/linuxonandroid/config.$system"
+    . "$config_path/config.$system"
   fi
 
   if mount | grep -q " $mnt "; then
     echo "$img already mounted"
-    if [ "$2" = "android" ] && $(mount | ! grep -q " $mnt/mnt/data "); then
-      echo "Mounting: System Parts ..."
-      mount -o bind $ANDROID_DATA "$mnt/mnt/data"
-      mount -o bind $ANDROID_ROOT "$mnt/mnt/system"
-      #if [ -d "/sbin" ]; then
-      #  mount -o bind /sbin "$mnt/mnt/sbin"
-      #fi
-    fi
+    #if [ "$arg_android" == "true" ] && $(mount | ! grep -q " $mnt/mnt/data "); then
+    #if [ "$arg_android" == "true" ] && ! mountpoint -q "$mnt/mnt/data "; then
+    #  echo "Mounting: System Parts ..."
+    #  mount -o bind "$ANDROID_DATA" "$mnt/mnt/data"
+    #  mount -o bind "$ANDROID_ROOT" "$mnt/mnt/system"
+    #  #if [ -d "/sbin" ]; then
+    #  #  mount -o bind /sbin "$mnt/mnt/sbin"
+    #  #fi
+    #fi
     exit 2
   fi
 
@@ -94,6 +267,7 @@ mount)
   fi
 
   if [ "$native" == "true" ]; then
+    echo "Mounting: Native mount ..."
     mount -t "$imgtype" $imgoptions "$partition" "$mnt"
   else
     echo "Mounting: Loopback mount ..."
@@ -306,7 +480,7 @@ install)
   if [ ! -e "$home/linuxonandroid/config.$system" ] || [ "$force" == "true" ] || [ "$refresh" == "true" ]; then
     echo "Creating config files ..."
     mkdir -p /data/local/linuxonandroid
-    echo "kit=\"$kit\"" > "/data/local/linuxonandroid/config.$system"
+    #echo "kit=\"$kit\"" > "/data/local/linuxonandroid/config.$system"
     echo "img=\"$img\"" >> "/data/local/linuxonandroid/config.$system"
 
     if [ "$refresh" == "true" ] && [ ! -z "$mnt" ]; then
@@ -319,6 +493,11 @@ install)
       echo "native=\"$native\"" >> "$home/linuxonandroid/config.$system"
     else
       echo "#native=\"false\"" >> "$home/linuxonandroid/config.$system"
+    fi
+    if [ "$refresh" == "true" ] && [ ! -z "$architecture" ]; then
+      echo "architecture=\"$architecture\"" >> "$home/linuxonandroid/config.$system"
+    else
+      echo "#architecture=\"debian\"" >> "$home/linuxonandroid/config.$system"
     fi
     if [ "$refresh" == "true" ] && [ ! -z "$partition" ]; then
       echo "partition=\"$partition\"" >> "$home/linuxonandroid/config.$system"
@@ -351,8 +530,15 @@ install)
       echo "mountdefault=\"sdcard\" #,intern,android,images,images:default,images:system,images::wireshark,ram" >> "/data/local/linuxonandroid/config.$system"
     fi
     if [ "$refresh" == "true" ] && [ ! -z "$wlan_if" ]; then
-      echo "wlan_if=\"$wlan_if\"" >> "/data/local/linuxonandroid/
-
+      echo "wlan_if=\"$wlan_if\"" >> "/data/local/linuxonandroid/config.$system"
+    else
+      echo "#wlan_if=\"wlan0\"" >> "/data/local/linuxonandroid/config.$system"
+    fi
+    if [ "$refresh" == "true" ] && [ ! -z "$mobile_if" ]; then
+      echo "mobile_if=\"$mobile_if\"" >> "/data/local/linuxonandroid/config.$system"
+    else
+      echo "#mobile_if=\"rmnet0\"" >> "/data/local/linuxonandroid/config.$system"
+    fi
     if [ "$refresh" == "true" ] && [ ! -z "$shell" ]; then
       echo "shell=\"$shell\"" >> "/data/local/linuxonandroid/config.$system"
     else
@@ -369,6 +555,23 @@ passwd)
   chroot "$mnt" /usr/bin/passwd $2
 
 ;;
+status)
+  echo "Memory (RAM):"
+  free
+  echo ""
+  echo "Swap:"
+  cat /proc/swaps
+
+;;
+statistic)
+  # my wishlist to install + is currently installed
+  echo "Memory (RAM):"
+  free
+  echo ""
+  echo "Swap:"
+  cat /proc/swaps
+
+;;
 space)
   echo "Memory (RAM):"
   free
@@ -378,8 +581,8 @@ space)
 
 ;;
 network)
-  "$0" mount
-  chroot "$mnt" /root/scripts/network.sh "$wlan_if" $@
+  #"$0" mount
+  #chroot "$mnt" /root/scripts/network.sh "$wlan_if" $@
 
 ;;
 hardinstall)
